### ISSUE TITLE
Support for client cert auth

### ISSUE THREAD

**Issue by rp-** [IBM/etcd-java#24]
Is there some documentation on how this should work?
What should the certificate file contain or which format should it have?
I mean the cert file I pass to the ComposeTrustManagerFactory.

**Comment by njhill** [comment]
@rp- actually I think client auth (mutual TLS) currently isn't exposed, this was likely just an oversight.

I will add support soon so that it's in the next release, the change to do this will be very small.

You shouldn't need to use `ComposeTrustManagerFactory`, that will likely be deprecated at some point.

**Comment by rp-** [comment]
Thank you!

I thought I was holding it wrong.

**Comment by njhill** [comment]
@rp- PTAL at 39102afbb9f4d8e9ee7b0c5bf533b91d85c9e42f

For example:
```java
EtcdClient client = EtcdClient.forEndpoint(...)
    .withTlsConfig(bld -> bld.keyManager(...).trustManager(...))
    .build();
```
You can see all the builder options here: https://netty.io/4.1/api/io/netty/handler/ssl/SslContextBuilder.html

I haven't added support to the declarative json-based config yet, maybe will do that in a future update.

**Comment by rp-** [comment]
Thank you Nick!
got it working, new release would be cool.

**Comment by njhill** [comment]
@rp- FYI version [0.0.13](https://github.com/IBM/etcd-java/releases/tag/v0.0.13) is now released
