### ISSUE TITLE
Unused Field

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [IBM/etcd-java#25]
https://github.com/IBM/etcd-java/blob/06890ea6fd0d82210ce85929591ac51c8b836ba4/src/main/java/com/ibm/etcd/client/kv/EtcdKvClient.java#L91
This field is never used.

**Comment by njhill** [comment]
Thanks @QiAnXinCodeSafe, this was kind of intentional It's not currently used but is something that we were considering to automatically identify obviously idempotent transactions (which could then benefit from more aggressive failure retries). My hesitation was related to the additional allocations involved.

I guess there would be no harm in commenting it out for now though...
