### ISSUE TITLE
Lock method, how to distinguish the success and failure of lock acquisition

### ISSUE THREAD

**Issue by 15135198365** [IBM/etcd-java#37]
```
LockResponse lr = client.getLockClient().lock(ByteString.copyFromUtf8(lockName)).withLease(id).sync();

lr .toString() --->
lockKey:header {
  cluster_id: 14841639068965178418
  member_id: 10276657743932975437
  revision: 58
  raft_term: 6
}
key: "123/694d7328a85b6ef9"

lockKey:header {
  cluster_id: 14841639068965178418
  member_id: 10276657743932975437
  revision: 60
  raft_term: 6
}
key: "123/694d7328a85b6efc"
```

how to distinguish the success and failure of lock acquisition？

**Comment by njhill** [comment]
@15135198365 sorry for delayed response. If the request returns successfully then the lock was successfully acquired. It will block otherwise until the lock is available, or cancellation or deadline expiry.

See https://github.com/etcd-io/etcd/blob/master/etcdserver/api/v3lock/v3lockpb/v3lock.proto#L15

**Comment by njhill** [comment]
Closing for now, @15135198365 let me know if you have further questions.
