### ISSUE TITLE
CVE-2021-21295 - netty-codec-4.1.51.Final.jar is vulnerable 

### ISSUE THREAD

**Issue by venkataramanam** [IBM/etcd-java#51]
We are seeing a vulnerability, [CVE-2021-21295](https://nvd.nist.gov/vuln/detail/CVE-2021-21295), being reported against one of the dependency jars (`netty-codec-4.1.51.Final.jar`)  pulled in by version `com.ibm.etcd:etcd-java:0.0.18`. Could you please upgrade the `netty-version` to `4.1.62.Final` that would be great.

Thanks
Venkat

**Comment by njhill** [comment]
@venkataramanam this library uses netty via gRPC and gRPC is not vulnerable to this CVE (see comment in the [grpc-java 1.36.1 release notes](https://github.com/grpc/grpc-java/releases/tag/v1.36.1)).

I've generally been keeping the netty dependency aligned with the version used by the current gRPC version, so might not update to the latest netty version quite yet given the vulnerability doesn't apply. However you are free to override the depdency in your consuming app (I would recommend using the bom artifact), this will work fine but you must also override the gRPC version to 1.36.1+ due to a netty incompatibility prior to that (also recommend bom for this).

**Comment by venkataramanam** [comment]
@njhill Great thanks for the response. We will take care of aligning grpc and netty versions when the grpc `1.36.1+` is  made available. Feel free to close the issue or keep it open when you decide to upgrade the netty version.
